include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

variables:
  STACK: confluent

.deploy:
  variables:
    IMAGE_NAME: confluentinc/cp-zookeeper
    IMAGE_TAG: ${CONFLUENT_VERSION}
