version: '3.5'

services:
  zookeeper-2:
    environment:
      - KAFKA_HEAP_OPTS=-Xmx128m -Xms128m
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          memory: 205M

volumes:
  zk-data-vol:
    name: ${ZK_DATA_VOL_NAME:-zk-2-data-vol}

  zk-log-vol:
    name: ${ZK_LOG_VOL_NAME:-zk-2-log-vol}
