version: '3.5'

services:
  zookeeper:
    environment:
      KAFKA_HEAP_OPTS: -Xmx256m -Xms256m
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.001'
          memory: 410M

x-prod-default-volume:
  &prod-default-volume
  driver: 'cloudstor:aws'
  driver_opts:
    backing: relocatable
    size: 1
    ebstype: gp2

volumes:
  zk-data-vol:
    << : *prod-default-volume
    name: ${ZK_DATA_VOL_NAME:-zk-{{.Task.Slot}}-data-vol}

  zk-log-vol:
    << : *prod-default-volume
    name: ${ZK_LOG_VOL_NAME:-zk-{{.Task.Slot}}-log-vol}
