version: '3.5'

services:
  zookeeper-2:
    environment:
      KAFKA_HEAP_OPTS: -Xmx128m -Xms128m
    deploy:
      placement:
        constraints:
          - node.hostname == ${ZK_2_PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-256M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-205M}

volumes:
  zk-data-vol:
    name: ${ZK_DATA_VOL_NAME:-zk-2-data-vol}

  zk-log-vol:
    name: ${ZK_LOG_VOL_NAME:-zk-2-log-vol}
