version: '3.5'

services:
  zookeeper-1:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    hostname: zk-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      KAFKA_JMX_HOSTNAME: zk-1
      KAFKA_OPTS: -javaagent:${JMX_PROMETHEUS_JAVAAGENT_PATH}=${JMX_HTTP_PORT}:${JMX_PROMETHEUS_CONFIG_PATH}
      ZOOKEEPER_CLIENT_PORT:
      KAFKA_JMX_PORT:
      ZOOKEEPER_TICK_TIME:
      ZOOKEEPER_INIT_LIMIT:
      ZOOKEEPER_SYNC_LIMIT:
      ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT:
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL:
      ZOOKEEPER_SERVERS:
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL:
    networks:
      kafka-net:
        aliases:
          - zk-1
      metric-net:
    configs:
      - source: jmx-prometheus-javaagent
        target: ${JMX_PROMETHEUS_JAVAAGENT_PATH}
      - source: jmx-prometheus-config
        target: ${JMX_PROMETHEUS_CONFIG_PATH}
    volumes:
      - zk-data-vol:/var/lib/zookeeper/data
      - zk-log-vol:/var/lib/zookeeper/log
      - zk-secrets-vol:/etc/zookeeper/secrets
    healthcheck:
      test: echo ruok | nc localhost ${ZK_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:10s}
      retries: ${HEALTHCHECK_RETRIES:10}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    attachable: ${KAFKA_NET_ATTACHABLE:-true}

  metric-net:
    name: ${METRIC_NET_NAME:-metric-net}
    driver: ${METRIC_NET_DRIVER:-overlay}
    external: true

volumes:
  zk-secrets-vol:
    name: ${ZK_SECRETS_VOL_NAME:-zk-1-secrets-vol}

configs:
  jmx-prometheus-javaagent:
    name: ${JMX_PROMETHEUS_JAVA_AGENT_NAME:-jmx-prometheus-javaagent-0.11.0}
    file: ./config/jmx_prometheus_javaagent-0.11.0.jar

  jmx-prometheus-config:
    name: ${JMX_PROMETHEUS_CONFIG_NAME:-jmx-prometheus-config-0.11.0}
    file: ./config/config.yaml
